defaults: &defaults
  adapter: postgresql
  template: template0
  host: localhost

development:
  <<: *defaults
  database: kbirthday_development

test:
  <<: *defaults
  min_messages: warning #magic sauce
  database: kbirthday_test
